# 00-eth0.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      set-name: eth0
      match:
        driver: "smsc95xx"
      addresses: [192.168.13.4/24]
      routes:
      - to: default
        via: 192.168.13.1
      nameservers:
        addresses: [192.168.13.1]
